---

- name: 'Python dependencies installed'
  yum:
    name:
      - python2-cryptography
    state: present

- name: 'NGINX repository added'
  copy:
    src:   nginx.repo
    dest:  /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode:  '0644'

- name: 'NGINX installed'
  yum:
    name:
      - nginx
    state:        present
    update_cache: true

- name: 'NGINX main config copied'
  copy:
    src:   nginx.conf
    dest:  /etc/nginx/nginx.conf
    owner: root
    group: root
    mode:  0644
  notify: restart_nginx

- name: 'SSL certs directory created'
  file:
    path:  "{{ ssl_dir }}"
    state: directory
    mode: '0644'

- name: 'Private key generated'
  openssl_privatekey:
    path:   "{{ ssl_key }}"
    size:   "4096"
    type:   "RSA"
    backup: yes

- name: 'Cert request generated'
  openssl_csr:
    path:              "{{ ssl_csr }}"
    privatekey_path:   "{{ ssl_key }}"
    country_name:      "RU"
    organization_name: "Tensor, OOO"
    email_address:     "admin@tensor.ru"
    common_name:       "localhost"

- name: 'SelfSigned cert generated'
  openssl_certificate:
    path:            "{{ ssl_cert }}"
    privatekey_path: "{{ ssl_key }}"
    csr_path:        "{{ ssl_csr }}"
    provider:        selfsigned

- name: 'Site config created from template'
  template:
    src:  nginx.conf.j2
    dest: /etc/nginx/conf.d/tls.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart_nginx

- name: "Index page created from template"
  template:
    src:   index.html.j2
    dest:  /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode:  0644
  notify: restart_nginx

- name: ensure nginx is enabled and started
  service:
    name:    nginx
    state:   started
    enabled: true

- name: insert firewalld rule for nginx
  firewalld:
    port:      "{{ https_port }}/tcp"
    permanent: true
    state:     enabled
    immediate: true
  ignore_errors: true
